# Partially generated by google gemini

from Motors import L298NMotorDriver
import lgpio
import time
from Util import *
from enum import Enum 


class pidController:
    def encoder_left_callback(self, chip, gpio, level, timestamp):
        self.encoder_count["left"] += 1
        # print("[left]: Encoder count =", self.encoder_count["left"])

    def encoder_right_callback(self, chip, gpio, level, timestamp):
        self.encoder_count["right"] += 1
        # print("[right]: Encoder count =", self.encoder_count["right"])

    def ir_callback(self, chip, gpio, level, timestamp):
            if level == 0: # Falling edge (1 -> 0)
                self.object_detected = True
                print("Object detected!!")
            else:
                self.object_detected = False
                print("Object gone!!")

    def __init__(self, chip, motor_driver: L298NMotorDriver, encoder_l_pin, encoder_r_pin, ir_pin, sonar):
        self.motor_driver = motor_driver
        self.sonar = sonar
        self.encoder_count = {"left": 0, "right": 0}
        self.speeds = {"left": 0, "right": 0}
        self.object_detected = False

        self.state = PID_State.IDLE
        self.state_values = {}
        
        # --- PID Constants ---
        self.Kp = 1.5  # Proportional 
        self.Ki = 0.03 # Integral
        self.Kd = 0.5  # Derivative

        # --- PID State variables ---
        self.integral = 0
        self.prev_error = 0

        # Register callbacks
        lgpio.gpio_claim_alert(chip, encoder_l_pin, lgpio.RISING_EDGE)
        self.cb_left = lgpio.callback(chip, encoder_l_pin, lgpio.RISING_EDGE, self.encoder_left_callback)

        lgpio.gpio_claim_alert(chip, encoder_r_pin, lgpio.RISING_EDGE)
        self.cb_right = lgpio.callback(chip, encoder_r_pin, lgpio.RISING_EDGE, self.encoder_right_callback)

        lgpio.gpio_claim_alert(chip, ir_pin, lgpio.BOTH_EDGES)
        self.cb_ir = lgpio.callback(chip, ir_pin, lgpio.BOTH_EDGES, self.ir_callback)


    def move_straight(self, speed, distance):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """
        # Reset encoder counts and PID state for a clean run

        self.encoder_count = {"left": 0, "right": 0}
        self.integral = 0
        self.prev_error = 0

        self.state = PID_State.STRAIGHT
        self.state_values = {"target_speed": speed, "distance": distance}

        # Tell the L298N library to start moving forward
        self.motor_driver.motor_left_rotate(speed)
        self.motor_driver.motor_right_rotate(speed)

    def rotate_right(self, degrees):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """
        # Reset encoder counts and PID state for a clean run
        self.encoder_count = {"left": 0, "right": 0}
        self.integral = 0
        self.prev_error = 0

        # Encoder counts to reach
        counts = degrees/6

        self.state = PID_State.TURNING_RIGHT
        self.state_values = {"counts": counts}

        # Tell the L298N library to start rotating
        self.motor_driver.motor_left_rotate(TURN_SPEED)
        self.motor_driver.motor_right_rotate(-TURN_SPEED)

    def rotate_left(self, degrees):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """
        # Reset encoder counts and PID state for a clean run
        self.encoder_count = {"left": 0, "right": 0}
        self.integral = 0
        self.prev_error = 0

        # Encoder counts to reach
        counts = degrees/6

        self.state = PID_State.TURNING_LEFT
        self.state_values = {"counts": counts}

        # Tell the L298N library to start rotating
        self.motor_driver.motor_left_rotate(-TURN_SPEED)
        self.motor_driver.motor_right_rotate(TURN_SPEED)

    def update(self):
        if self.state == PID_State.IDLE or self.state == PID_State.WAITING:
            self.motor_driver.stop_all()

        if self.state == PID_State.STRAIGHT:
            self.straight_update()
        elif self.state == PID_State.TURNING_RIGHT:
            self.rotate_right_update()
        elif self.state == PID_State.WAITING:
            self.wait_update()

        elif self.state == PID_State.COAST:
            self.motor_driver.coast()

    def wait(self, seconds):
        self.state = PID_State.WAITING
        self.state_values = {"wait_start": time.time(), "wait_duration": seconds}

    def wait_update(self):
        if self.state != PID_State.WAITING:
            return

        start = self.state_values["wait_start"]
        duration = self.state_values["wait_duration"]

        if (time.time() - start) >= duration:
            self.state = PID_State.IDLE

    def rotate_right_update(self):
        # The control loop
        if (self.encoder_count["left"] + self.encoder_count["right"]) >= self.state_values["counts"]:
            print("Rotation complete. Final Encoder Counts:", self.encoder_count)
            self.state = PID_State.IDLE
            return

        # 1. Calculate the Error
        # If positive: Left is spinning faster. If negative: Right is spinning faster.
        error = self.encoder_count["left"] - self.encoder_count["right"]

        # 2. Calculate PID terms
        P = self.Kp * error
        self.integral += error
        I = self.Ki * self.integral
        D = self.Kd * (error - self.prev_error)

        # 3. Calculate total adjustment
        adjustment = P + I + D
        self.prev_error = error

        # 4. Apply adjustment to the base speeds
        # If error is positive, we subtract adjustment from left and add to right.
        left_speed = TURN_SPEED - adjustment
        right_speed = -(TURN_SPEED + adjustment)

        # print(f"({left_speed}, {right_speed})")

        # 5. Apply the new speeds to the motors
        self.motor_driver.motor_left_rotate(left_speed)
        self.motor_driver.motor_right_rotate(right_speed)

    def rotate_left_update(self):
        # The control loop
        if (self.encoder_count["left"] + self.encoder_count["right"]) >= self.state_values["counts"]:
            print("Rotation complete. Final Encoder Counts:", self.encoder_count)
            self.state = PID_State.IDLE
            return
    
        # 1. Calculate the Error
        # If positive: Left is spinning faster. If negative: Right is spinning faster.
        error = self.encoder_count["left"] - self.encoder_count["right"]

        # 2. Calculate PID terms
        P = self.Kp * error
        self.integral += error
        I = self.Ki * self.integral
        D = self.Kd * (error - self.prev_error)

        # 3. Calculate total adjustment
        adjustment = P + I + D
        self.prev_error = error

        # 4. Apply adjustment to the base speeds
        # If error is positive, we subtract adjustment from left and add to right.
        left_speed = -(TURN_SPEED - adjustment)
        right_speed = (TURN_SPEED + adjustment)

        # print(f"({left_speed}, {right_speed})") 

        # 5. Apply the new speeds to the motors
        self.motor_driver.motor_left_rotate(left_speed)
        self.motor_driver.motor_right_rotate(right_speed)

    def straight_update(self):
        if self.state != PID_State.STRAIGHT:
            return

        speed = self.state_values["target_speed"]
        distance = self.state_values["distance"]

        counts = (self.encoder_count["left"] + self.encoder_count["right"]) // 2
        distance_traveled = counts * COUNT_TO_METERS

        if distance_traveled >= distance:
            print("Movement complete. Final Encoder Counts:", self.encoder_count)
            self.state = PID_State.IDLE
            self.motor_driver.stop_all()
            self.state_values = {
                "last_state_success": True,
                "final_encoder_count": self.encoder_count,
                "final_distance_traveled": distance_traveled
            }
            return
        
        # Only stop if we're moving forward and detect an object
        if self.sonar.distance > 0 and self.sonar.distance < DISTANCE_THRESHOLD and speed > 0:
            print("Object detected during straight movement! Stopping.")
            self.state = PID_State.IDLE
            counts = (self.encoder_count["left"] + self.encoder_count["right"]) // 2
            final_distance = counts * COUNT_TO_METERS
            self.state_values = {
                "last_state_success": False,
                "reason": "object_detected",
                "final_encoder_count": self.encoder_count,
                "final_distance": final_distance,
            }
            return

        # 1. Calculate error
        # If positive: Left is spinning faster. If negative: Right is spinning faster.
        error = self.encoder_count["left"] - self.encoder_count["right"]

        # 2. Calculate PID terms
        P = self.Kp * error
        self.integral += error
        I = self.Ki * self.integral
        D = self.Kd * (error - self.prev_error)

        # 3. Calculate total adjustment
        adjustment = P + I + D
        if speed < 0:
            # Backwards
            adjustment = -adjustment

        self.prev_error = error

        # 4. Apply adjustment to the base speeds
        # If error is positive, we subtract adjustment from left and add to right.
        left_speed = speed - adjustment
        right_speed = speed + adjustment

        # print(f"({left_speed}, {right_speed})") 

        # 5. Apply the new speeds to the motors
        self.motor_driver.motor_left_rotate(left_speed)
        self.motor_driver.motor_right_rotate(right_speed)

