# Partially generated by google gemini

from Motors import L298NMotorDriver
import lgpio
import time
from Util import *
from enum import Enum 

LOG = False

LEFT_WHEEL = "left"
RIGHT_WHEEL = "right"

def log(s):
    if LOG:
        print(s)

class pidController:

    def encoder_callback(self, wheel, timestamp):
        self.encoder_count[wheel] += 1

        elapsed = (timestamp - self.last_update[wheel]) / 1_000_000_000.

        ALPHA = 0.7 # TODO: tune

        measured_speed = 1. / elapsed
        prev_speed = self.speeds[wheel]

        self.speeds[wheel] = ALPHA*measured_speed + (1-ALPHA)*prev_speed
        log(f"{wheel}: speed={self.speeds[wheel]:.2f}")

        self.last_update[wheel] = timestamp
        # log(f"[{wheel}]: Encoder count = {self.encoder_count[wheel]}")

    def encoder_left_callback(self, chip, gpio, level, timestamp):
        self.encoder_callback(LEFT_WHEEL, timestamp)

    def encoder_right_callback(self, chip, gpio, level, timestamp):
        self.encoder_callback(RIGHT_WHEEL, timestamp)

    def __init__(self, chip, motor_driver: L298NMotorDriver, encoder_l_pin, encoder_r_pin, sonar):
        self.motor_driver = motor_driver
        self.sonar = sonar
        self.encoder_count = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}

        self.signals = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.speeds = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}

        self.speed_history = []
        self.signal_history = []

        self.last_update = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.object_detected = False

        self.state = PID_State.IDLE
        self.state_values = {}

        # --- PID Constants ---
        self.Kp = 0.30  # Proportional
        self.Ki = 0.0001 # Integral
        self.Kd = 1.1  # Derivative

        # --- PID State variables ---
        self.integrals = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.prev_error = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}

        # --- Track update time for calculating wheel speed
        self.pid_start = -1

        # Register callbacks
        lgpio.gpio_claim_alert(chip, encoder_l_pin, lgpio.RISING_EDGE)
        self.cb_left = lgpio.callback(chip, encoder_l_pin, lgpio.RISING_EDGE, self.encoder_left_callback)

        lgpio.gpio_claim_alert(chip, encoder_r_pin, lgpio.RISING_EDGE)
        self.cb_right = lgpio.callback(chip, encoder_r_pin, lgpio.RISING_EDGE, self.encoder_right_callback)

    def close(self):
        self.cb_left.cancel()
        self.cb_right.cancel()

    def reset_pid(self):
        """Reset encoder counts and PID state for a clean run"""

        self.encoder_count = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.integrals = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.prev_error = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}

        self.signals = {LEFT_WHEEL: MOTOR_SPEED, RIGHT_WHEEL:MOTOR_SPEED}
        self.speeds = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}
        self.last_update = {LEFT_WHEEL: 0, RIGHT_WHEEL: 0}

        self.pid_start = time.perf_counter()


    def move_straight(self, speed, distance):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """

        self.reset_pid()

        self.state = PID_State.STRAIGHT
        self.state_values = {"target_speed": speed, "distance": distance}

        # Tell the L298N library to start moving forward
        self.motor_driver.motor_left_rotate(self.signals[LEFT_WHEEL])
        self.motor_driver.motor_right_rotate(self.signals[RIGHT_WHEEL])

    def rotate_right(self, degrees):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """

        self.reset_pid()

        # Encoder counts to reach
        counts = degrees/5

        self.state = PID_State.TURNING_RIGHT
        self.state_values = {"target_speed": TURN_SPEED, "counts": counts}

        # Tell the L298N library to start rotating
        self.motor_driver.motor_left_rotate(-TURN_SPEED)
        self.motor_driver.motor_right_rotate(TURN_SPEED)

    def rotate_left(self, degrees):
        """
        Drives the robot straight forward using PID control to balance motor speeds.
        """
        
        self.reset_pid()

        # Encoder counts to reach
        counts = degrees/6

        self.state = PID_State.TURNING_LEFT
        self.state_values = {"target_speed": TURN_SPEED, "counts": counts}

        # Tell the L298N library to start rotating
        self.motor_driver.motor_left_rotate(-TURN_SPEED)
        self.motor_driver.motor_right_rotate(TURN_SPEED)

    def update(self):
        if self.state == PID_State.IDLE or self.state == PID_State.WAITING:
            self.motor_driver.stop_all()

        if self.state == PID_State.STRAIGHT:
            self.straight_update()
        elif self.state == PID_State.TURNING_RIGHT:
            self.rotate_right_update()
        elif self.state == PID_State.TURNING_LEFT:
            self.rotate_left_update()
        elif self.state == PID_State.WAITING:
            self.wait_update()

        elif self.state == PID_State.COAST:
            self.motor_driver.coast()

        self.sonar.trigger()

    def wait(self, seconds):
        self.state = PID_State.WAITING
        self.state_values = {"wait_start": time.time(), "wait_duration": seconds}

    def wait_update(self):
        if self.state != PID_State.WAITING:
            return

        start = self.state_values["wait_start"]
        duration = self.state_values["wait_duration"]

        if (time.time() - start) >= duration:
            self.state = PID_State.IDLE

    def rotate_right_update(self):

        if self.state != PID_State.TURNING_RIGHT:
            print("BAD!")
            return

        if (self.encoder_count[LEFT_WHEEL] + self.encoder_count[RIGHT_WHEEL]) >= self.state_values["counts"]:
            print("Rotation complete. Final Encoder Counts:", self.encoder_count)
            self.motor_driver.stop_all()
            self.state = PID_State.IDLE
            return

        left_speed_adj = self.pid_one_wheel(LEFT_WHEEL)
        right_speed_adj = self.pid_one_wheel(RIGHT_WHEEL)

        # Apply the new speeds to the motors
        self.signals[LEFT_WHEEL] += left_speed_adj
        self.signals[RIGHT_WHEEL] += right_speed_adj
        self.signals[LEFT_WHEEL] = min(100, max(0, self.signals[LEFT_WHEEL]))
        self.signals[RIGHT_WHEEL] = min(100, max(0, self.signals[RIGHT_WHEEL]))

        self.motor_driver.motor_left_rotate(-self.signals[LEFT_WHEEL])
        self.motor_driver.motor_right_rotate(self.signals[RIGHT_WHEEL])

        self.speed_history.append(self.speeds.copy())
        self.signal_history.append(self.signals.copy())
        print(self.signals[LEFT_WHEEL], self.signals[RIGHT_WHEEL])

    def rotate_left_update(self):
        # The control loop
        if (self.encoder_count[LEFT_WHEEL] + self.encoder_count[RIGHT_WHEEL]) >= self.state_values["counts"]:
            print("Rotation complete. Final Encoder Counts:", self.encoder_count)
            self.state = PID_State.IDLE
            return
    
        # 1. Calculate the Error
        # If positive: Left is spinning faster. If negative: Right is spinning faster.
        error = self.encoder_count[LEFT_WHEEL] - self.encoder_count[RIGHT_WHEEL]

        # 2. Calculate PID terms
        P = self.Kp * error
        self.integral["left"] += error
        I = self.Ki * self.integral["left"]
        D = self.Kd * (error - self.prev_error["left"])

        # 3. Calculate total adjustment
        adjustment = P + I + D
        self.prev_error["left"] = error

        # 4. Apply adjustment to the base speeds
        # If error is positive, we subtract adjustment from left and add to right.
        left_speed = -(TURN_SPEED - adjustment)
        right_speed = (TURN_SPEED + adjustment)

        # print(f"({left_speed}, {right_speed})") 

        # 5. Apply the new speeds to the motors
        self.motor_driver.motor_left_rotate(left_speed)
        self.motor_driver.motor_right_rotate(right_speed)

    def pid_one_wheel(self, wheel: str) -> int:

        target_speed = self.state_values["target_speed"]

        # Give slightly more time before adjusting
        elapsed = time.perf_counter() - self.pid_start
        if elapsed < 0.1:
            return 0

        # 1. Calculate error
        error = self.speeds[wheel] - abs(target_speed)

        log(f"speed={self.speeds[wheel]:.3f}")

        # 2. Calculate PID terms
        P = self.Kp * error
        if elapsed > .2: # Don't accumulate error for a short time
            self.integrals[wheel] += error
        I = self.Ki * self.integrals[wheel]
        D = self.Kd * (error - self.prev_error[wheel])

        # 3. Calculate total adjustment
        adjustment = -(P + I + D)

        print(f"[{wheel}]: error={error:.2f}, integral={self.integrals[wheel]:.2f}, ({P:.2f}, {I:.2f}, {D:.2f}) |{adjustment:.2f}|, future={self.signals[wheel] + adjustment:.2f}")

        self.prev_error[wheel] = error

        # 4. Apply adjustment to the base speeds
        return adjustment

    def straight_update(self):
        if self.state != PID_State.STRAIGHT:
            return

        speed = self.state_values["target_speed"]
        distance = self.state_values["distance"]

        counts = (self.encoder_count[LEFT_WHEEL] + self.encoder_count[RIGHT_WHEEL]) // 2
        distance_traveled = counts * COUNT_TO_METERS

        if distance_traveled >= distance:
            print("Movement complete. Final Encoder Counts:", self.encoder_count)
            self.state = PID_State.IDLE
            self.motor_driver.stop_all()
            self.state_values = {
                "last_state_success": True,
                "final_encoder_count": self.encoder_count,
                "final_distance_traveled": distance_traveled
            }
            return

        # Only stop if we're moving forward and detect an object
        if self.sonar.distance > 0 and self.sonar.distance < DISTANCE_THRESHOLD and speed > 0:
            print("Object detected during straight movement! Stopping.")
            self.motor_driver.stop_all()
            self.state = PID_State.IDLE
            counts = (self.encoder_count[LEFT_WHEEL] + self.encoder_count[RIGHT_WHEEL]) // 2
            final_distance = counts * COUNT_TO_METERS
            self.state_values = {
                "last_state_success": False,
                "reason": "object_detected",
                "final_encoder_count": self.encoder_count,
                "final_distance_traveled": final_distance,
            }
            return

        left_speed_adj = self.pid_one_wheel(LEFT_WHEEL)
        right_speed_adj = self.pid_one_wheel(RIGHT_WHEEL)

        elapsed = time.perf_counter() - self.pid_start
        # log(f"elapsed={elapsed:.2f}s: ({left_speed}, {right_speed})")

        # Apply the new speeds to the motors

        self.signals[LEFT_WHEEL] += left_speed_adj
        self.signals[RIGHT_WHEEL] += right_speed_adj
        self.signals[LEFT_WHEEL] = min(100, max(0, self.signals[LEFT_WHEEL]))
        self.signals[RIGHT_WHEEL] = min(100, max(0, self.signals[RIGHT_WHEEL]))

        sign = -1 if self.state_values["target_speed"] < 0 else 1
        self.motor_driver.motor_left_rotate(sign*self.signals[LEFT_WHEEL])
        self.motor_driver.motor_right_rotate(sign*self.signals[RIGHT_WHEEL])
        print(sign*self.signals[LEFT_WHEEL], sign*self.signals[RIGHT_WHEEL])

        self.speed_history.append(self.speeds.copy())
        self.signal_history.append(self.signals.copy())
